### ISSUE TITLE
process.execPath errors on Windows

### ISSUE THREAD

**Issue by danday74** [jochemstoel/nodejs-system-sleep#8]
Hi there. Thanks for this library.

I've noticed that deasync sleep doesn't work on some platforms and you have provided a fallback in case it fails.

I want to ensure the fallback catch block is reliable so I played with your code to force use of the fallback.

But on Windows I get this error:

```
Error: Command failed: C:\Program Files\nodejs\node.exe -e "setTimeout(function () { return true; }, 1000);"
'C:\Program' is not recognized as an internal or external command

```

This is because of the space in the path name.

Changing your catch block code from this:

```
var cmd = process.execPath + " -e \"setTimeout(function () { return true; }, " + interval + ");\""
require('child_process').execSync(cmd)
```

To this:

```
var cmd = "\"" + process.execPath + "\" -e \"setTimeout(function () { return true; }, " + interval + ");\""
require('child_process').execSync(cmd)
```

Fixes the space in the path issue on Windows. Please could you fix this. Thanks

This change simply wraps process.execPath in quotes to prevent spaces in the path from breaking your code.

**Comment by jochemstoel** [comment]
Hi. This issue was already reported and fixed two days ago by GitHub user [16Bitt](https://github.com/16Bitt) who made the same changes as you did and sent a pull request. I changed it to use backticks in stead of + symbols but in essence it is the same. 

The repository on GitHub had already been updated but I forgot to publish the new version on NPM as well.

I have now also published the latest version 1.3.6 to NPM. 
https://www.npmjs.com/package/system-sleep

Thank you for the reminder. Let me know  if you run into any trouble.
